### ISSUE TITLE
Installation Issue..

### ISSUE THREAD

**Issue by daviddelmonte** [middlemac/middlemac#1]
Hi, thanks for providing this tool. I am getting this message in the console when trying to install the gem:

`You don't have write permissions for the /Library/Ruby/Gems/2.6.0 directory.`

Not sure if I can/should change permissions. If I should, what would be correct? Thanks for any help.

**Comment by balthisar** [comment]
Are you using RVM? Or native built-in Ruby? For built-in, you'll have to used `sudo` to install.

**Comment by daviddelmonte** [comment]
Thank you Sir, sudo did the trick.
