### ISSUE TITLE
HPDBookIconPath ignored in config.rb file

### ISSUE THREAD

**Issue by PierL** [middlemac/middlemac#2]
I have been trying to change the icon for the help book in the config.rb file, as described in the documentation. I am using the following:

        :free =>
            {
                :CFBundleID       => 'com.sample.project.pro.help',
                :HPDBookIconPath  => 'SharedGlobalAssets/images/myicon_32x32.png',
                :CFBundleName     => 'New Project',
                :ProductName      => 'New Project Pro',
                :ProductVersion   => version_app || '3.1.0',
                :ProductURI       => 'http://www.sample.com',
                :ProductCopyright => '© 2018 Jim Derry. All rights reserved.',
                :features =>
                    {
                        :feature_advertise_pro        => false,
                        :feature_performs_miracles    => true,
                        :feature_insults_user         => false,
                        :feature_shows_pink_rectangle => true,
                    }
            },

However, the icon set in the configuration file is ignored in the landing page and I always get the default one SharedGlobalAssets/convention/icon_32x32.png. I even tried to place the icon set in the convention folder.

Am I doing something wrong?

**Comment by balthisar** [comment]
@PierL, sorry I missed this for so long. I'm hoping you've had the issue resolved, but if not, here's the explanation.

The `HDPBookIconPath` isn't the icon on the landing page. It's used by macOS when showing help book icons in the list of Help Book in HelpViewer. This is why it's such a small, low quality icon.

The landing page icon _is_ static, and always links to `icon_256x256` in `SharedGlobalAssets/convention`. I can see what that's a pain in the neck. If you're using `target-magic-images` (for example, using `all-my_image.png` will be substituted with `targetname-my_image.png`) then you can fix this in `SharedGlobalAssets/_layouts/layout-apple-modern.haml`. Just change this:

~~~
    - if landing
      = image_tag "icon_256x256"
~~~

to this:

~~~
    - if landing
      = image_tag "all-icon_256x256"
~~~

The simply name the images you want to use with the prefix matching your target, and you'll be all set.

In fact, I'm going to make this change to 3.1.1 and release it shortly. It seems like the right thing to do.
