### ISSUE TITLE
Sandbox

### ISSUE THREAD

**Issue by freysie** [middlemac/middlemac#6]
Is Middlemac supposed to Just Work™ with sandboxed Mac apps?

After building a help book and adding it to my app, help viewer just shows a blank page when opened.

Looking at Console, I see this:

> WebProcessProxy::checkURLReceivedFromWebProcess: Received an unexpected URL from the web process
> WebPageProxy::Ignoring request to load this main resource because it is outside the sandbox

The title of the help viewer shows the correct title of my help bundle. Searching in help viewer works, I can see pages in the results, but when I click on them, I get another blank page and the same console output. 

PS: Thank you for this great project!

**Comment by balthisar** [comment]
It absolutely _should_ work with sandboxed apps; my main applications are sandboxed. Do you have a minimal project you can post so I can try to reproduce?

**Comment by freysie** [comment]
Thanks for your swift reply! Here’s a repro repo: https://github.com/freyaariel/middlemac-issue-6-reproduction

Not sure if it’s relevant to mention that I’m using `rbenv` instead of `rvm` for managing Ruby versions.

**Comment by freysie** [comment]
It suddenly started working after updating to latest macOS and Xcode. Thanks again!
